[package]
name = "obs"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[features]
default = []
serde = ["dep:serde", "num-rational/serde", "serde?/derive", "time/serde-human-readable"]
tracing = ["dep:tracing-subscriber", "tracing-subscriber?/fmt"]

[dependencies]
anyhow = "1.0.68"
bitflags = "1.3.2"
libobs-sys = { path = "../libobs-sys" }
log = { version = "0.4.17", features = ["std"] }
num-rational = { version = "0.4.1", default-features = false }
serde = { version = "1.0.152", optional = true }
strum = { version = "0.24.1", features = ["derive"] }
time = "0.3.17"
tracing-subscriber = { version = "0.3.16", default-features = false, optional = true }
