[package]
name = "obs"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[features]
default = []
tracing = ["tracing-subscriber"]

[dependencies]
anyhow = "1.0.58"
bitflags = "1.3.2"
libobs-sys = { path = "../libobs-sys" }
log = { version = "0.4.17", features = ["std"] }
strum = { version = "0.24.1", features = ["derive"] }
time = "0.3.11"
tracing-subscriber = { version = "0.3.14", default-features = false, features = ["fmt"], optional = true }
