[package]
name = "obs"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[features]
default = []
serde = ["dep:serde", "num-rational/serde", "serde?/derive", "time/serde-human-readable"]
tracing = ["dep:tracing-subscriber", "tracing-subscriber?/fmt"]

[dependencies]
anyhow = "1.0.71"
bitflags = { version = "2.3.3", features = ["serde"] }
libobs-sys = { path = "../libobs-sys" }
log = { version = "0.4.19", features = ["std"] }
num-rational = { version = "0.4.1", default-features = false }
serde = { version = "1.0.169", optional = true }
strum = { version = "0.25.0", features = ["derive"] }
time = "0.3.23"
tracing-subscriber = { version = "0.3.17", default-features = false, optional = true }
