[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "api" },
    { allow = ["AGPL-3.0"], name = "api-legacy" },
    { allow = ["AGPL-3.0"], name = "libobs-sys" },
    { allow = ["AGPL-3.0"], name = "obs" },
    { allow = ["AGPL-3.0"], name = "obs-client" },
    { allow = ["AGPL-3.0"], name = "obs-remote" },
    { allow = ["AGPL-3.0"], name = "obs-rust" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip = [
    { name = "bitflags", version = "1" },
    { name = "hashbrown", version = "0.12" },
    { name = "indexmap", version = "1" },
    { name = "prettyplease", version = "0.1" },
    { name = "socket2", version = "0.4" },
    { name = "syn", version = "1" },
]
