[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "libobs-sys" },
    { allow = ["AGPL-3.0"], name = "obs" },
    { allow = ["AGPL-3.0"], name = "obs-client" },
    { allow = ["AGPL-3.0"], name = "obs-remote" },
    { allow = ["AGPL-3.0"], name = "obs-remote-apiv4" },
    { allow = ["AGPL-3.0"], name = "obs-remote-apiv5" },
    { allow = ["AGPL-3.0"], name = "obs-rust" },
    { allow = ["Zlib"], name = "adler32" },
]

[bans]
skip = [
	{ name = "itoa", version = "=0.4.8" },
    { name = "miniz_oxide", version = "=0.3.7" },
]
