[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "api" },
    { allow = ["AGPL-3.0"], name = "api-legacy" },
    { allow = ["AGPL-3.0"], name = "libobs-sys" },
    { allow = ["AGPL-3.0"], name = "obs" },
    { allow = ["AGPL-3.0"], name = "obs-client" },
    { allow = ["AGPL-3.0"], name = "obs-remote" },
    { allow = ["AGPL-3.0"], name = "obs-rust" },
    { allow = ["Zlib"], name = "adler32" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]
