[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "api" },
    { allow = ["AGPL-3.0"], name = "api-legacy" },
    { allow = ["AGPL-3.0"], name = "libobs-sys" },
    { allow = ["AGPL-3.0"], name = "obs" },
    { allow = ["AGPL-3.0"], name = "obs-client" },
    { allow = ["AGPL-3.0"], name = "obs-gradient-sourcer" },
    { allow = ["AGPL-3.0"], name = "obs-remote" },
    { allow = ["AGPL-3.0"], name = "obs-rust" },
    { allow = ["Unicode-3.0"], name = "unicode-ident" },
]

[bans]
skip = [
    "bitflags@1",
    "getrandom@0.2",
    "hashbrown@0.12",
    "indexmap@1",
    "itertools@0.13",
    "tower@0.4",
    "wasi@0.11",
]
skip-tree = [
    { crate = "windows-sys@0.52", depth = 3 },
]
