use std::{ffi::c_void, ptr::NonNull};

use bitflags::bitflags;

use crate::{
    data::Data,
    encoder::Encoder,
    output::Output,
    service::Service,
    source::Source,
    util::{FfiToString, StringToFfi},
};

pub struct Hotkey {
    raw: NonNull<libobs_sys::obs_hotkey_t>,
}

impl Hotkey {
    pub(crate) fn from_raw(raw: *mut libobs_sys::obs_hotkey_t) -> Self {
        Self {
            raw: unsafe { NonNull::new_unchecked(raw) },
        }
    }

    pub fn by_name(name: &str) -> Option<Self> {
        struct Param<'a> {
            name: &'a str,
            result: Option<Hotkey>,
        }

        unsafe extern "C" fn callback(
            param: *mut c_void,
            _id: libobs_sys::obs_hotkey_id,
            key: *mut libobs_sys::obs_hotkey_t,
        ) -> bool {
            let param = &mut *param.cast::<Param<'_>>();
            let key = Hotkey::from_raw(key);

            if key.name() == param.name {
                param.result = Some(key);
                false
            } else {
                true
            }
        }

        let mut param = Param { name, result: None };

        unsafe {
            libobs_sys::obs_enum_hotkeys(Some(callback), (&mut param as *mut Param<'_>).cast())
        };

        param.result
    }

    pub fn id(&self) -> u64 {
        unsafe { libobs_sys::obs_hotkey_get_id(self.raw.as_ptr()) }
    }

    pub fn name(&self) -> String {
        unsafe { libobs_sys::obs_hotkey_get_name(self.raw.as_ptr()) }.into_string()
    }

    pub fn description(&self) -> String {
        unsafe { libobs_sys::obs_hotkey_get_description(self.raw.as_ptr()) }.into_string()
    }

    pub fn registerer_type(&self) -> HotkeyRegisterer {
        HotkeyRegisterer::from_native(unsafe {
            libobs_sys::obs_hotkey_get_registerer_type(self.raw.as_ptr())
        })
    }

    pub fn trigger_routed_callback(&self, pressed: bool) {
        let id = self.id();
        unsafe { libobs_sys::obs_hotkey_trigger_routed_callback(id, pressed) };
    }
}

pub struct HotkeyBinding {
    raw: NonNull<libobs_sys::obs_hotkey_binding_t>,
}

impl HotkeyBinding {
    fn from_raw(raw: *mut libobs_sys::obs_hotkey_binding_t) -> Self {
        Self {
            raw: unsafe { NonNull::new_unchecked(raw) },
        }
    }

    pub fn hotkey(&self) -> Hotkey {
        Hotkey::from_raw(unsafe { libobs_sys::obs_hotkey_binding_get_hotkey(self.raw.as_ptr()) })
    }

    pub fn hotkey_id(&self) -> u64 {
        unsafe { libobs_sys::obs_hotkey_binding_get_hotkey_id(self.raw.as_ptr()) }
    }

    pub fn key_combination(&self) -> Option<KeyCombination> {
        KeyCombination::from_native(unsafe {
            libobs_sys::obs_hotkey_binding_get_key_combination(self.raw.as_ptr())
        })
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug)]
pub enum HotkeyRegisterer {
    Frontend,
    Source,
    Output,
    Encoder,
    Service,
    Unknown(u32),
}

impl HotkeyRegisterer {
    fn from_native(value: libobs_sys::obs_hotkey_registerer_type::Type) -> Self {
        use libobs_sys::obs_hotkey_registerer_type::*;

        match value {
            OBS_HOTKEY_REGISTERER_FRONTEND => Self::Frontend,
            OBS_HOTKEY_REGISTERER_SOURCE => Self::Source,
            OBS_HOTKEY_REGISTERER_OUTPUT => Self::Output,
            OBS_HOTKEY_REGISTERER_ENCODER => Self::Encoder,
            OBS_HOTKEY_REGISTERER_SERVICE => Self::Service,
            v => Self::Unknown(v as u32),
        }
    }
}

bitflags! {
    pub struct InteractionFlags: u32 {
        const NONE = libobs_sys::obs_interaction_flags::INTERACT_NONE as u32;
        const CAPS_KEY = libobs_sys::obs_interaction_flags::INTERACT_CAPS_KEY as u32;
        const SHIFT_KEY = libobs_sys::obs_interaction_flags::INTERACT_SHIFT_KEY as u32;
        const CONTROL_KEY = libobs_sys::obs_interaction_flags::INTERACT_CONTROL_KEY as u32;
        const ALT_KEY = libobs_sys::obs_interaction_flags::INTERACT_ALT_KEY as u32;
        const MOUSE_LEFT = libobs_sys::obs_interaction_flags::INTERACT_MOUSE_LEFT as u32;
        const MOUSE_MIDDLE = libobs_sys::obs_interaction_flags::INTERACT_MOUSE_MIDDLE as u32;
        const MOUSE_RIGHT = libobs_sys::obs_interaction_flags::INTERACT_MOUSE_RIGHT as u32;
        const COMMAND_KEY = libobs_sys::obs_interaction_flags::INTERACT_COMMAND_KEY as u32;
        const NUMLOCK_KEY = libobs_sys::obs_interaction_flags::INTERACT_NUMLOCK_KEY as u32;
        const IS_KEY_PAD = libobs_sys::obs_interaction_flags::INTERACT_IS_KEY_PAD as u32;
        const IS_LEFT = libobs_sys::obs_interaction_flags::INTERACT_IS_LEFT as u32;
        const IS_RIGHT = libobs_sys::obs_interaction_flags::INTERACT_IS_RIGHT as u32;
    }
}

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Clone, Copy)]
#[repr(u32)]
pub enum Key {
    Return,
    Enter,
    Escape,
    Tab,
    Backtab,
    Backspace,
    Insert,
    Delete,
    Pause,
    Print,
    Sysreq,
    Clear,
    Home,
    End,
    Left,
    Up,
    Right,
    Down,
    Pageup,
    Pagedown,
    Shift,
    Control,
    Meta,
    Alt,
    Altgr,
    Capslock,
    Numlock,
    Scrolllock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,
    Menu,
    HyperL,
    HyperR,
    Help,
    DirectionL,
    DirectionR,
    Space,
    Exclam,
    Quotedbl,
    Numbersign,
    Dollar,
    Percent,
    Ampersand,
    Apostrophe,
    Parenleft,
    Parenright,
    Asterisk,
    Plus,
    Comma,
    Minus,
    Period,
    Slash,
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Numequal,
    Numasterisk,
    Numplus,
    Numcomma,
    Numminus,
    Numperiod,
    Numslash,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Colon,
    Semicolon,
    Quote,
    Less,
    Equal,
    Greater,
    Question,
    At,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Bracketleft,
    Backslash,
    Bracketright,
    Asciicircum,
    Underscore,
    Quoteleft,
    Braceleft,
    Bar,
    Braceright,
    Asciitilde,
    Nobreakspace,
    Exclamdown,
    Cent,
    Sterling,
    Currency,
    Yen,
    Brokenbar,
    Section,
    Diaeresis,
    Copyright,
    Ordfeminine,
    Guillemotleft,
    Notsign,
    Hyphen,
    Registered,
    Macron,
    Degree,
    Plusminus,
    Twosuperior,
    Threesuperior,
    Acute,
    Mu,
    Paragraph,
    Periodcentered,
    Cedilla,
    Onesuperior,
    Masculine,
    Guillemotright,
    Onequarter,
    Onehalf,
    Threequarters,
    Questiondown,
    Agrave,
    Aacute,
    Acircumflex,
    Atilde,
    Adiaeresis,
    Aring,
    Ae,
    Ccedilla,
    Egrave,
    Eacute,
    Ecircumflex,
    Ediaeresis,
    Igrave,
    Iacute,
    Icircumflex,
    Idiaeresis,
    Eth,
    Ntilde,
    Ograve,
    Oacute,
    Ocircumflex,
    Otilde,
    Odiaeresis,
    Multiply,
    Ooblique,
    Ugrave,
    Uacute,
    Ucircumflex,
    Udiaeresis,
    Yacute,
    Thorn,
    Ssharp,
    Division,
    Ydiaeresis,
    MultiKey,
    Codeinput,
    Singlecandidate,
    Multiplecandidate,
    Previouscandidate,
    ModeSwitch,
    Kanji,
    Muhenkan,
    Henkan,
    Romaji,
    Hiragana,
    Katakana,
    HiraganaKatakana,
    Zenkaku,
    Hankaku,
    ZenkakuHankaku,
    Touroku,
    Massyo,
    KanaLock,
    KanaShift,
    EisuShift,
    EisuToggle,
    Hangul,
    HangulStart,
    HangulEnd,
    HangulHanja,
    HangulJamo,
    HangulRomaja,
    HangulJeonja,
    HangulBanja,
    HangulPrehanja,
    HangulPosthanja,
    HangulSpecial,
    DeadGrave,
    DeadAcute,
    DeadCircumflex,
    DeadTilde,
    DeadMacron,
    DeadBreve,
    DeadAbovedot,
    DeadDiaeresis,
    DeadAbovering,
    DeadDoubleacute,
    DeadCaron,
    DeadCedilla,
    DeadOgonek,
    DeadIota,
    DeadVoicedSound,
    DeadSemivoicedSound,
    DeadBelowdot,
    DeadHook,
    DeadHorn,
    Back,
    Forward,
    Stop,
    Refresh,
    Volumedown,
    Volumemute,
    Volumeup,
    Bassboost,
    Bassup,
    Bassdown,
    Trebleup,
    Trebledown,
    Mediaplay,
    Mediastop,
    Mediaprevious,
    Medianext,
    Mediarecord,
    Mediapause,
    Mediatoggleplaypause,
    Homepage,
    Favorites,
    Search,
    Standby,
    Openurl,
    Launchmail,
    Launchmedia,
    Launch0,
    Launch1,
    Launch2,
    Launch3,
    Launch4,
    Launch5,
    Launch6,
    Launch7,
    Launch8,
    Launch9,
    Launcha,
    Launchb,
    Launchc,
    Launchd,
    Launche,
    Launchf,
    Launchg,
    Launchh,
    Monbrightnessup,
    Monbrightnessdown,
    Keyboardlightonoff,
    Keyboardbrightnessup,
    Keyboardbrightnessdown,
    Poweroff,
    Wakeup,
    Eject,
    Screensaver,
    Www,
    Memo,
    Lightbulb,
    Shop,
    History,
    Addfavorite,
    Hotlinks,
    Brightnessadjust,
    Finance,
    Community,
    Audiorewind,
    Backforward,
    Applicationleft,
    Applicationright,
    Book,
    Cd,
    Calculator,
    Todolist,
    Cleargrab,
    Close,
    Copy,
    Cut,
    Display,
    Dos,
    Documents,
    Excel,
    Explorer,
    Game,
    Go,
    Itouch,
    Logoff,
    Market,
    Meeting,
    Menukb,
    Menupb,
    Mysites,
    News,
    Officehome,
    Option,
    Paste,
    Phone,
    Calendar,
    Reply,
    Reload,
    Rotatewindows,
    Rotationpb,
    Rotationkb,
    Save,
    Send,
    Spell,
    Splitscreen,
    Support,
    Taskpane,
    Terminal,
    Tools,
    Travel,
    Video,
    Word,
    Xfer,
    Zoomin,
    Zoomout,
    Away,
    Messenger,
    Webcam,
    Mailforward,
    Pictures,
    Music,
    Battery,
    Bluetooth,
    Wlan,
    Uwb,
    Audioforward,
    Audiorepeat,
    Audiorandomplay,
    Subtitle,
    Audiocycletrack,
    Time,
    Hibernate,
    View,
    Topmenu,
    Powerdown,
    Suspend,
    Contrastadjust,
    Medialast,
    Call,
    Camera,
    Camerafocus,
    Context1,
    Context2,
    Context3,
    Context4,
    Flip,
    Hangup,
    No,
    Select,
    Yes,
    Togglecallhangup,
    Voicedial,
    Lastnumberredial,
    Execute,
    Printer,
    Play,
    Sleep,
    Zoom,
    Cancel,
    Mouse1,
    Mouse2,
    Mouse3,
    Mouse4,
    Mouse5,
    Mouse6,
    Mouse7,
    Mouse8,
    Mouse9,
    Mouse10,
    Mouse11,
    Mouse12,
    Mouse13,
    Mouse14,
    Mouse15,
    Mouse16,
    Mouse17,
    Mouse18,
    Mouse19,
    Mouse20,
    Mouse21,
    Mouse22,
    Mouse23,
    Mouse24,
    Mouse25,
    Mouse26,
    Mouse27,
    Mouse28,
    Mouse29,
    BackslashRt102,
    Open,
    Find,
    Redo,
    Undo,
    Front,
    Props,
    VkCancel,
    Key0x07,
    Key0x0a,
    Key0x0b,
    Key0x0e,
    Key0x0f,
    Key0x16,
    VkJunja,
    VkFinal,
    Key0x1a,
    VkAccept,
    VkModechange,
    VkSelect,
    VkPrint,
    VkExecute,
    VkHelp,
    Key0x30,
    Key0x31,
    Key0x32,
    Key0x33,
    Key0x34,
    Key0x35,
    Key0x36,
    Key0x37,
    Key0x38,
    Key0x39,
    Key0x3a,
    Key0x3b,
    Key0x3c,
    Key0x3d,
    Key0x3e,
    Key0x3f,
    Key0x40,
    Key0x41,
    Key0x42,
    Key0x43,
    Key0x44,
    Key0x45,
    Key0x46,
    Key0x47,
    Key0x48,
    Key0x49,
    Key0x4a,
    Key0x4b,
    Key0x4c,
    Key0x4d,
    Key0x4e,
    Key0x4f,
    Key0x50,
    Key0x51,
    Key0x52,
    Key0x53,
    Key0x54,
    Key0x55,
    Key0x56,
    Key0x57,
    Key0x58,
    Key0x59,
    Key0x5a,
    VkLwin,
    VkRwin,
    VkApps,
    Key0x5e,
    VkSleep,
    VkSeparator,
    Key0x88,
    Key0x89,
    Key0x8a,
    Key0x8b,
    Key0x8c,
    Key0x8d,
    Key0x8e,
    Key0x8f,
    VkOemFjJisho,
    VkOemFjLoya,
    VkOemFjRoya,
    Key0x97,
    Key0x98,
    Key0x99,
    Key0x9a,
    Key0x9b,
    Key0x9c,
    Key0x9d,
    Key0x9e,
    Key0x9f,
    VkLshift,
    VkRshift,
    VkLcontrol,
    VkRcontrol,
    VkLmenu,
    VkRmenu,
    VkBrowserBack,
    VkBrowserForward,
    VkBrowserRefresh,
    VkBrowserStop,
    VkBrowserSearch,
    VkBrowserFavorites,
    VkBrowserHome,
    VkVolumeMute,
    VkVolumeDown,
    VkVolumeUp,
    VkMediaNextTrack,
    VkMediaPrevTrack,
    VkMediaStop,
    VkMediaPlayPause,
    VkLaunchMail,
    VkLaunchMediaSelect,
    VkLaunchApp1,
    VkLaunchApp2,
    Key0xb8,
    Key0xb9,
    Key0xc1,
    Key0xc2,
    Key0xc3,
    Key0xc4,
    Key0xc5,
    Key0xc6,
    Key0xc7,
    Key0xc8,
    Key0xc9,
    Key0xca,
    Key0xcb,
    Key0xcc,
    Key0xcd,
    Key0xce,
    Key0xcf,
    Key0xd0,
    Key0xd1,
    Key0xd2,
    Key0xd3,
    Key0xd4,
    Key0xd5,
    Key0xd6,
    Key0xd7,
    Key0xd8,
    Key0xd9,
    Key0xda,
    VkOem8,
    Key0xe0,
    VkOemAx,
    VkIcoHelp,
    VkIco00,
    VkProcesskey,
    VkIcoClear,
    VkPacket,
    Key0xe8,
    VkOemReset,
    VkOemJump,
    VkOemPa1,
    VkOemPa2,
    VkOemPa3,
    VkOemWsctrl,
    VkOemCusel,
    VkOemAttn,
    VkOemFinish,
    VkOemCopy,
    VkOemAuto,
    VkOemEnlw,
    VkAttn,
    VkCrsel,
    VkExsel,
    VkEreof,
    VkPlay,
    VkZoom,
    VkNoname,
    VkPa1,
    VkOemClear,
    Unknown,
}

impl Key {
    fn from_native(value: libobs_sys::obs_key::Type) -> Option<Self> {
        use libobs_sys::obs_key::*;

        #[allow(non_upper_case_globals)]
        Some(match value {
            OBS_KEY_NONE => return None,
            OBS_KEY_RETURN => Self::Return,
            OBS_KEY_ENTER => Self::Enter,
            OBS_KEY_ESCAPE => Self::Escape,
            OBS_KEY_TAB => Self::Tab,
            OBS_KEY_BACKTAB => Self::Backtab,
            OBS_KEY_BACKSPACE => Self::Backspace,
            OBS_KEY_INSERT => Self::Insert,
            OBS_KEY_DELETE => Self::Delete,
            OBS_KEY_PAUSE => Self::Pause,
            OBS_KEY_PRINT => Self::Print,
            OBS_KEY_SYSREQ => Self::Sysreq,
            OBS_KEY_CLEAR => Self::Clear,
            OBS_KEY_HOME => Self::Home,
            OBS_KEY_END => Self::End,
            OBS_KEY_LEFT => Self::Left,
            OBS_KEY_UP => Self::Up,
            OBS_KEY_RIGHT => Self::Right,
            OBS_KEY_DOWN => Self::Down,
            OBS_KEY_PAGEUP => Self::Pageup,
            OBS_KEY_PAGEDOWN => Self::Pagedown,
            OBS_KEY_SHIFT => Self::Shift,
            OBS_KEY_CONTROL => Self::Control,
            OBS_KEY_META => Self::Meta,
            OBS_KEY_ALT => Self::Alt,
            OBS_KEY_ALTGR => Self::Altgr,
            OBS_KEY_CAPSLOCK => Self::Capslock,
            OBS_KEY_NUMLOCK => Self::Numlock,
            OBS_KEY_SCROLLLOCK => Self::Scrolllock,
            OBS_KEY_F1 => Self::F1,
            OBS_KEY_F2 => Self::F2,
            OBS_KEY_F3 => Self::F3,
            OBS_KEY_F4 => Self::F4,
            OBS_KEY_F5 => Self::F5,
            OBS_KEY_F6 => Self::F6,
            OBS_KEY_F7 => Self::F7,
            OBS_KEY_F8 => Self::F8,
            OBS_KEY_F9 => Self::F9,
            OBS_KEY_F10 => Self::F10,
            OBS_KEY_F11 => Self::F11,
            OBS_KEY_F12 => Self::F12,
            OBS_KEY_F13 => Self::F13,
            OBS_KEY_F14 => Self::F14,
            OBS_KEY_F15 => Self::F15,
            OBS_KEY_F16 => Self::F16,
            OBS_KEY_F17 => Self::F17,
            OBS_KEY_F18 => Self::F18,
            OBS_KEY_F19 => Self::F19,
            OBS_KEY_F20 => Self::F20,
            OBS_KEY_F21 => Self::F21,
            OBS_KEY_F22 => Self::F22,
            OBS_KEY_F23 => Self::F23,
            OBS_KEY_F24 => Self::F24,
            OBS_KEY_F25 => Self::F25,
            OBS_KEY_F26 => Self::F26,
            OBS_KEY_F27 => Self::F27,
            OBS_KEY_F28 => Self::F28,
            OBS_KEY_F29 => Self::F29,
            OBS_KEY_F30 => Self::F30,
            OBS_KEY_F31 => Self::F31,
            OBS_KEY_F32 => Self::F32,
            OBS_KEY_F33 => Self::F33,
            OBS_KEY_F34 => Self::F34,
            OBS_KEY_F35 => Self::F35,
            OBS_KEY_MENU => Self::Menu,
            OBS_KEY_HYPER_L => Self::HyperL,
            OBS_KEY_HYPER_R => Self::HyperR,
            OBS_KEY_HELP => Self::Help,
            OBS_KEY_DIRECTION_L => Self::DirectionL,
            OBS_KEY_DIRECTION_R => Self::DirectionR,
            OBS_KEY_SPACE => Self::Space,
            OBS_KEY_EXCLAM => Self::Exclam,
            OBS_KEY_QUOTEDBL => Self::Quotedbl,
            OBS_KEY_NUMBERSIGN => Self::Numbersign,
            OBS_KEY_DOLLAR => Self::Dollar,
            OBS_KEY_PERCENT => Self::Percent,
            OBS_KEY_AMPERSAND => Self::Ampersand,
            OBS_KEY_APOSTROPHE => Self::Apostrophe,
            OBS_KEY_PARENLEFT => Self::Parenleft,
            OBS_KEY_PARENRIGHT => Self::Parenright,
            OBS_KEY_ASTERISK => Self::Asterisk,
            OBS_KEY_PLUS => Self::Plus,
            OBS_KEY_COMMA => Self::Comma,
            OBS_KEY_MINUS => Self::Minus,
            OBS_KEY_PERIOD => Self::Period,
            OBS_KEY_SLASH => Self::Slash,
            OBS_KEY_0 => Self::Key0,
            OBS_KEY_1 => Self::Key1,
            OBS_KEY_2 => Self::Key2,
            OBS_KEY_3 => Self::Key3,
            OBS_KEY_4 => Self::Key4,
            OBS_KEY_5 => Self::Key5,
            OBS_KEY_6 => Self::Key6,
            OBS_KEY_7 => Self::Key7,
            OBS_KEY_8 => Self::Key8,
            OBS_KEY_9 => Self::Key9,
            OBS_KEY_NUMEQUAL => Self::Numequal,
            OBS_KEY_NUMASTERISK => Self::Numasterisk,
            OBS_KEY_NUMPLUS => Self::Numplus,
            OBS_KEY_NUMCOMMA => Self::Numcomma,
            OBS_KEY_NUMMINUS => Self::Numminus,
            OBS_KEY_NUMPERIOD => Self::Numperiod,
            OBS_KEY_NUMSLASH => Self::Numslash,
            OBS_KEY_NUM0 => Self::Num0,
            OBS_KEY_NUM1 => Self::Num1,
            OBS_KEY_NUM2 => Self::Num2,
            OBS_KEY_NUM3 => Self::Num3,
            OBS_KEY_NUM4 => Self::Num4,
            OBS_KEY_NUM5 => Self::Num5,
            OBS_KEY_NUM6 => Self::Num6,
            OBS_KEY_NUM7 => Self::Num7,
            OBS_KEY_NUM8 => Self::Num8,
            OBS_KEY_NUM9 => Self::Num9,
            OBS_KEY_COLON => Self::Colon,
            OBS_KEY_SEMICOLON => Self::Semicolon,
            OBS_KEY_QUOTE => Self::Quote,
            OBS_KEY_LESS => Self::Less,
            OBS_KEY_EQUAL => Self::Equal,
            OBS_KEY_GREATER => Self::Greater,
            OBS_KEY_QUESTION => Self::Question,
            OBS_KEY_AT => Self::At,
            OBS_KEY_A => Self::A,
            OBS_KEY_B => Self::B,
            OBS_KEY_C => Self::C,
            OBS_KEY_D => Self::D,
            OBS_KEY_E => Self::E,
            OBS_KEY_F => Self::F,
            OBS_KEY_G => Self::G,
            OBS_KEY_H => Self::H,
            OBS_KEY_I => Self::I,
            OBS_KEY_J => Self::J,
            OBS_KEY_K => Self::K,
            OBS_KEY_L => Self::L,
            OBS_KEY_M => Self::M,
            OBS_KEY_N => Self::N,
            OBS_KEY_O => Self::O,
            OBS_KEY_P => Self::P,
            OBS_KEY_Q => Self::Q,
            OBS_KEY_R => Self::R,
            OBS_KEY_S => Self::S,
            OBS_KEY_T => Self::T,
            OBS_KEY_U => Self::U,
            OBS_KEY_V => Self::V,
            OBS_KEY_W => Self::W,
            OBS_KEY_X => Self::X,
            OBS_KEY_Y => Self::Y,
            OBS_KEY_Z => Self::Z,
            OBS_KEY_BRACKETLEFT => Self::Bracketleft,
            OBS_KEY_BACKSLASH => Self::Backslash,
            OBS_KEY_BRACKETRIGHT => Self::Bracketright,
            OBS_KEY_ASCIICIRCUM => Self::Asciicircum,
            OBS_KEY_UNDERSCORE => Self::Underscore,
            OBS_KEY_QUOTELEFT => Self::Quoteleft,
            OBS_KEY_BRACELEFT => Self::Braceleft,
            OBS_KEY_BAR => Self::Bar,
            OBS_KEY_BRACERIGHT => Self::Braceright,
            OBS_KEY_ASCIITILDE => Self::Asciitilde,
            OBS_KEY_NOBREAKSPACE => Self::Nobreakspace,
            OBS_KEY_EXCLAMDOWN => Self::Exclamdown,
            OBS_KEY_CENT => Self::Cent,
            OBS_KEY_STERLING => Self::Sterling,
            OBS_KEY_CURRENCY => Self::Currency,
            OBS_KEY_YEN => Self::Yen,
            OBS_KEY_BROKENBAR => Self::Brokenbar,
            OBS_KEY_SECTION => Self::Section,
            OBS_KEY_DIAERESIS => Self::Diaeresis,
            OBS_KEY_COPYRIGHT => Self::Copyright,
            OBS_KEY_ORDFEMININE => Self::Ordfeminine,
            OBS_KEY_GUILLEMOTLEFT => Self::Guillemotleft,
            OBS_KEY_NOTSIGN => Self::Notsign,
            OBS_KEY_HYPHEN => Self::Hyphen,
            OBS_KEY_REGISTERED => Self::Registered,
            OBS_KEY_MACRON => Self::Macron,
            OBS_KEY_DEGREE => Self::Degree,
            OBS_KEY_PLUSMINUS => Self::Plusminus,
            OBS_KEY_TWOSUPERIOR => Self::Twosuperior,
            OBS_KEY_THREESUPERIOR => Self::Threesuperior,
            OBS_KEY_ACUTE => Self::Acute,
            OBS_KEY_MU => Self::Mu,
            OBS_KEY_PARAGRAPH => Self::Paragraph,
            OBS_KEY_PERIODCENTERED => Self::Periodcentered,
            OBS_KEY_CEDILLA => Self::Cedilla,
            OBS_KEY_ONESUPERIOR => Self::Onesuperior,
            OBS_KEY_MASCULINE => Self::Masculine,
            OBS_KEY_GUILLEMOTRIGHT => Self::Guillemotright,
            OBS_KEY_ONEQUARTER => Self::Onequarter,
            OBS_KEY_ONEHALF => Self::Onehalf,
            OBS_KEY_THREEQUARTERS => Self::Threequarters,
            OBS_KEY_QUESTIONDOWN => Self::Questiondown,
            OBS_KEY_AGRAVE => Self::Agrave,
            OBS_KEY_AACUTE => Self::Aacute,
            OBS_KEY_ACIRCUMFLEX => Self::Acircumflex,
            OBS_KEY_ATILDE => Self::Atilde,
            OBS_KEY_ADIAERESIS => Self::Adiaeresis,
            OBS_KEY_ARING => Self::Aring,
            OBS_KEY_AE => Self::Ae,
            OBS_KEY_CCEDILLA => Self::Ccedilla,
            OBS_KEY_EGRAVE => Self::Egrave,
            OBS_KEY_EACUTE => Self::Eacute,
            OBS_KEY_ECIRCUMFLEX => Self::Ecircumflex,
            OBS_KEY_EDIAERESIS => Self::Ediaeresis,
            OBS_KEY_IGRAVE => Self::Igrave,
            OBS_KEY_IACUTE => Self::Iacute,
            OBS_KEY_ICIRCUMFLEX => Self::Icircumflex,
            OBS_KEY_IDIAERESIS => Self::Idiaeresis,
            OBS_KEY_ETH => Self::Eth,
            OBS_KEY_NTILDE => Self::Ntilde,
            OBS_KEY_OGRAVE => Self::Ograve,
            OBS_KEY_OACUTE => Self::Oacute,
            OBS_KEY_OCIRCUMFLEX => Self::Ocircumflex,
            OBS_KEY_OTILDE => Self::Otilde,
            OBS_KEY_ODIAERESIS => Self::Odiaeresis,
            OBS_KEY_MULTIPLY => Self::Multiply,
            OBS_KEY_OOBLIQUE => Self::Ooblique,
            OBS_KEY_UGRAVE => Self::Ugrave,
            OBS_KEY_UACUTE => Self::Uacute,
            OBS_KEY_UCIRCUMFLEX => Self::Ucircumflex,
            OBS_KEY_UDIAERESIS => Self::Udiaeresis,
            OBS_KEY_YACUTE => Self::Yacute,
            OBS_KEY_THORN => Self::Thorn,
            OBS_KEY_SSHARP => Self::Ssharp,
            OBS_KEY_DIVISION => Self::Division,
            OBS_KEY_YDIAERESIS => Self::Ydiaeresis,
            OBS_KEY_MULTI_KEY => Self::MultiKey,
            OBS_KEY_CODEINPUT => Self::Codeinput,
            OBS_KEY_SINGLECANDIDATE => Self::Singlecandidate,
            OBS_KEY_MULTIPLECANDIDATE => Self::Multiplecandidate,
            OBS_KEY_PREVIOUSCANDIDATE => Self::Previouscandidate,
            OBS_KEY_MODE_SWITCH => Self::ModeSwitch,
            OBS_KEY_KANJI => Self::Kanji,
            OBS_KEY_MUHENKAN => Self::Muhenkan,
            OBS_KEY_HENKAN => Self::Henkan,
            OBS_KEY_ROMAJI => Self::Romaji,
            OBS_KEY_HIRAGANA => Self::Hiragana,
            OBS_KEY_KATAKANA => Self::Katakana,
            OBS_KEY_HIRAGANA_KATAKANA => Self::HiraganaKatakana,
            OBS_KEY_ZENKAKU => Self::Zenkaku,
            OBS_KEY_HANKAKU => Self::Hankaku,
            OBS_KEY_ZENKAKU_HANKAKU => Self::ZenkakuHankaku,
            OBS_KEY_TOUROKU => Self::Touroku,
            OBS_KEY_MASSYO => Self::Massyo,
            OBS_KEY_KANA_LOCK => Self::KanaLock,
            OBS_KEY_KANA_SHIFT => Self::KanaShift,
            OBS_KEY_EISU_SHIFT => Self::EisuShift,
            OBS_KEY_EISU_TOGGLE => Self::EisuToggle,
            OBS_KEY_HANGUL => Self::Hangul,
            OBS_KEY_HANGUL_START => Self::HangulStart,
            OBS_KEY_HANGUL_END => Self::HangulEnd,
            OBS_KEY_HANGUL_HANJA => Self::HangulHanja,
            OBS_KEY_HANGUL_JAMO => Self::HangulJamo,
            OBS_KEY_HANGUL_ROMAJA => Self::HangulRomaja,
            OBS_KEY_HANGUL_JEONJA => Self::HangulJeonja,
            OBS_KEY_HANGUL_BANJA => Self::HangulBanja,
            OBS_KEY_HANGUL_PREHANJA => Self::HangulPrehanja,
            OBS_KEY_HANGUL_POSTHANJA => Self::HangulPosthanja,
            OBS_KEY_HANGUL_SPECIAL => Self::HangulSpecial,
            OBS_KEY_DEAD_GRAVE => Self::DeadGrave,
            OBS_KEY_DEAD_ACUTE => Self::DeadAcute,
            OBS_KEY_DEAD_CIRCUMFLEX => Self::DeadCircumflex,
            OBS_KEY_DEAD_TILDE => Self::DeadTilde,
            OBS_KEY_DEAD_MACRON => Self::DeadMacron,
            OBS_KEY_DEAD_BREVE => Self::DeadBreve,
            OBS_KEY_DEAD_ABOVEDOT => Self::DeadAbovedot,
            OBS_KEY_DEAD_DIAERESIS => Self::DeadDiaeresis,
            OBS_KEY_DEAD_ABOVERING => Self::DeadAbovering,
            OBS_KEY_DEAD_DOUBLEACUTE => Self::DeadDoubleacute,
            OBS_KEY_DEAD_CARON => Self::DeadCaron,
            OBS_KEY_DEAD_CEDILLA => Self::DeadCedilla,
            OBS_KEY_DEAD_OGONEK => Self::DeadOgonek,
            OBS_KEY_DEAD_IOTA => Self::DeadIota,
            OBS_KEY_DEAD_VOICED_SOUND => Self::DeadVoicedSound,
            OBS_KEY_DEAD_SEMIVOICED_SOUND => Self::DeadSemivoicedSound,
            OBS_KEY_DEAD_BELOWDOT => Self::DeadBelowdot,
            OBS_KEY_DEAD_HOOK => Self::DeadHook,
            OBS_KEY_DEAD_HORN => Self::DeadHorn,
            OBS_KEY_BACK => Self::Back,
            OBS_KEY_FORWARD => Self::Forward,
            OBS_KEY_STOP => Self::Stop,
            OBS_KEY_REFRESH => Self::Refresh,
            OBS_KEY_VOLUMEDOWN => Self::Volumedown,
            OBS_KEY_VOLUMEMUTE => Self::Volumemute,
            OBS_KEY_VOLUMEUP => Self::Volumeup,
            OBS_KEY_BASSBOOST => Self::Bassboost,
            OBS_KEY_BASSUP => Self::Bassup,
            OBS_KEY_BASSDOWN => Self::Bassdown,
            OBS_KEY_TREBLEUP => Self::Trebleup,
            OBS_KEY_TREBLEDOWN => Self::Trebledown,
            OBS_KEY_MEDIAPLAY => Self::Mediaplay,
            OBS_KEY_MEDIASTOP => Self::Mediastop,
            OBS_KEY_MEDIAPREVIOUS => Self::Mediaprevious,
            OBS_KEY_MEDIANEXT => Self::Medianext,
            OBS_KEY_MEDIARECORD => Self::Mediarecord,
            OBS_KEY_MEDIAPAUSE => Self::Mediapause,
            OBS_KEY_MEDIATOGGLEPLAYPAUSE => Self::Mediatoggleplaypause,
            OBS_KEY_HOMEPAGE => Self::Homepage,
            OBS_KEY_FAVORITES => Self::Favorites,
            OBS_KEY_SEARCH => Self::Search,
            OBS_KEY_STANDBY => Self::Standby,
            OBS_KEY_OPENURL => Self::Openurl,
            OBS_KEY_LAUNCHMAIL => Self::Launchmail,
            OBS_KEY_LAUNCHMEDIA => Self::Launchmedia,
            OBS_KEY_LAUNCH0 => Self::Launch0,
            OBS_KEY_LAUNCH1 => Self::Launch1,
            OBS_KEY_LAUNCH2 => Self::Launch2,
            OBS_KEY_LAUNCH3 => Self::Launch3,
            OBS_KEY_LAUNCH4 => Self::Launch4,
            OBS_KEY_LAUNCH5 => Self::Launch5,
            OBS_KEY_LAUNCH6 => Self::Launch6,
            OBS_KEY_LAUNCH7 => Self::Launch7,
            OBS_KEY_LAUNCH8 => Self::Launch8,
            OBS_KEY_LAUNCH9 => Self::Launch9,
            OBS_KEY_LAUNCHA => Self::Launcha,
            OBS_KEY_LAUNCHB => Self::Launchb,
            OBS_KEY_LAUNCHC => Self::Launchc,
            OBS_KEY_LAUNCHD => Self::Launchd,
            OBS_KEY_LAUNCHE => Self::Launche,
            OBS_KEY_LAUNCHF => Self::Launchf,
            OBS_KEY_LAUNCHG => Self::Launchg,
            OBS_KEY_LAUNCHH => Self::Launchh,
            OBS_KEY_MONBRIGHTNESSUP => Self::Monbrightnessup,
            OBS_KEY_MONBRIGHTNESSDOWN => Self::Monbrightnessdown,
            OBS_KEY_KEYBOARDLIGHTONOFF => Self::Keyboardlightonoff,
            OBS_KEY_KEYBOARDBRIGHTNESSUP => Self::Keyboardbrightnessup,
            OBS_KEY_KEYBOARDBRIGHTNESSDOWN => Self::Keyboardbrightnessdown,
            OBS_KEY_POWEROFF => Self::Poweroff,
            OBS_KEY_WAKEUP => Self::Wakeup,
            OBS_KEY_EJECT => Self::Eject,
            OBS_KEY_SCREENSAVER => Self::Screensaver,
            OBS_KEY_WWW => Self::Www,
            OBS_KEY_MEMO => Self::Memo,
            OBS_KEY_LIGHTBULB => Self::Lightbulb,
            OBS_KEY_SHOP => Self::Shop,
            OBS_KEY_HISTORY => Self::History,
            OBS_KEY_ADDFAVORITE => Self::Addfavorite,
            OBS_KEY_HOTLINKS => Self::Hotlinks,
            OBS_KEY_BRIGHTNESSADJUST => Self::Brightnessadjust,
            OBS_KEY_FINANCE => Self::Finance,
            OBS_KEY_COMMUNITY => Self::Community,
            OBS_KEY_AUDIOREWIND => Self::Audiorewind,
            OBS_KEY_BACKFORWARD => Self::Backforward,
            OBS_KEY_APPLICATIONLEFT => Self::Applicationleft,
            OBS_KEY_APPLICATIONRIGHT => Self::Applicationright,
            OBS_KEY_BOOK => Self::Book,
            OBS_KEY_CD => Self::Cd,
            OBS_KEY_CALCULATOR => Self::Calculator,
            OBS_KEY_TODOLIST => Self::Todolist,
            OBS_KEY_CLEARGRAB => Self::Cleargrab,
            OBS_KEY_CLOSE => Self::Close,
            OBS_KEY_COPY => Self::Copy,
            OBS_KEY_CUT => Self::Cut,
            OBS_KEY_DISPLAY => Self::Display,
            OBS_KEY_DOS => Self::Dos,
            OBS_KEY_DOCUMENTS => Self::Documents,
            OBS_KEY_EXCEL => Self::Excel,
            OBS_KEY_EXPLORER => Self::Explorer,
            OBS_KEY_GAME => Self::Game,
            OBS_KEY_GO => Self::Go,
            OBS_KEY_ITOUCH => Self::Itouch,
            OBS_KEY_LOGOFF => Self::Logoff,
            OBS_KEY_MARKET => Self::Market,
            OBS_KEY_MEETING => Self::Meeting,
            OBS_KEY_MENUKB => Self::Menukb,
            OBS_KEY_MENUPB => Self::Menupb,
            OBS_KEY_MYSITES => Self::Mysites,
            OBS_KEY_NEWS => Self::News,
            OBS_KEY_OFFICEHOME => Self::Officehome,
            OBS_KEY_OPTION => Self::Option,
            OBS_KEY_PASTE => Self::Paste,
            OBS_KEY_PHONE => Self::Phone,
            OBS_KEY_CALENDAR => Self::Calendar,
            OBS_KEY_REPLY => Self::Reply,
            OBS_KEY_RELOAD => Self::Reload,
            OBS_KEY_ROTATEWINDOWS => Self::Rotatewindows,
            OBS_KEY_ROTATIONPB => Self::Rotationpb,
            OBS_KEY_ROTATIONKB => Self::Rotationkb,
            OBS_KEY_SAVE => Self::Save,
            OBS_KEY_SEND => Self::Send,
            OBS_KEY_SPELL => Self::Spell,
            OBS_KEY_SPLITSCREEN => Self::Splitscreen,
            OBS_KEY_SUPPORT => Self::Support,
            OBS_KEY_TASKPANE => Self::Taskpane,
            OBS_KEY_TERMINAL => Self::Terminal,
            OBS_KEY_TOOLS => Self::Tools,
            OBS_KEY_TRAVEL => Self::Travel,
            OBS_KEY_VIDEO => Self::Video,
            OBS_KEY_WORD => Self::Word,
            OBS_KEY_XFER => Self::Xfer,
            OBS_KEY_ZOOMIN => Self::Zoomin,
            OBS_KEY_ZOOMOUT => Self::Zoomout,
            OBS_KEY_AWAY => Self::Away,
            OBS_KEY_MESSENGER => Self::Messenger,
            OBS_KEY_WEBCAM => Self::Webcam,
            OBS_KEY_MAILFORWARD => Self::Mailforward,
            OBS_KEY_PICTURES => Self::Pictures,
            OBS_KEY_MUSIC => Self::Music,
            OBS_KEY_BATTERY => Self::Battery,
            OBS_KEY_BLUETOOTH => Self::Bluetooth,
            OBS_KEY_WLAN => Self::Wlan,
            OBS_KEY_UWB => Self::Uwb,
            OBS_KEY_AUDIOFORWARD => Self::Audioforward,
            OBS_KEY_AUDIOREPEAT => Self::Audiorepeat,
            OBS_KEY_AUDIORANDOMPLAY => Self::Audiorandomplay,
            OBS_KEY_SUBTITLE => Self::Subtitle,
            OBS_KEY_AUDIOCYCLETRACK => Self::Audiocycletrack,
            OBS_KEY_TIME => Self::Time,
            OBS_KEY_HIBERNATE => Self::Hibernate,
            OBS_KEY_VIEW => Self::View,
            OBS_KEY_TOPMENU => Self::Topmenu,
            OBS_KEY_POWERDOWN => Self::Powerdown,
            OBS_KEY_SUSPEND => Self::Suspend,
            OBS_KEY_CONTRASTADJUST => Self::Contrastadjust,
            OBS_KEY_MEDIALAST => Self::Medialast,
            OBS_KEY_CALL => Self::Call,
            OBS_KEY_CAMERA => Self::Camera,
            OBS_KEY_CAMERAFOCUS => Self::Camerafocus,
            OBS_KEY_CONTEXT1 => Self::Context1,
            OBS_KEY_CONTEXT2 => Self::Context2,
            OBS_KEY_CONTEXT3 => Self::Context3,
            OBS_KEY_CONTEXT4 => Self::Context4,
            OBS_KEY_FLIP => Self::Flip,
            OBS_KEY_HANGUP => Self::Hangup,
            OBS_KEY_NO => Self::No,
            OBS_KEY_SELECT => Self::Select,
            OBS_KEY_YES => Self::Yes,
            OBS_KEY_TOGGLECALLHANGUP => Self::Togglecallhangup,
            OBS_KEY_VOICEDIAL => Self::Voicedial,
            OBS_KEY_LASTNUMBERREDIAL => Self::Lastnumberredial,
            OBS_KEY_EXECUTE => Self::Execute,
            OBS_KEY_PRINTER => Self::Printer,
            OBS_KEY_PLAY => Self::Play,
            OBS_KEY_SLEEP => Self::Sleep,
            OBS_KEY_ZOOM => Self::Zoom,
            OBS_KEY_CANCEL => Self::Cancel,
            OBS_KEY_MOUSE1 => Self::Mouse1,
            OBS_KEY_MOUSE2 => Self::Mouse2,
            OBS_KEY_MOUSE3 => Self::Mouse3,
            OBS_KEY_MOUSE4 => Self::Mouse4,
            OBS_KEY_MOUSE5 => Self::Mouse5,
            OBS_KEY_MOUSE6 => Self::Mouse6,
            OBS_KEY_MOUSE7 => Self::Mouse7,
            OBS_KEY_MOUSE8 => Self::Mouse8,
            OBS_KEY_MOUSE9 => Self::Mouse9,
            OBS_KEY_MOUSE10 => Self::Mouse10,
            OBS_KEY_MOUSE11 => Self::Mouse11,
            OBS_KEY_MOUSE12 => Self::Mouse12,
            OBS_KEY_MOUSE13 => Self::Mouse13,
            OBS_KEY_MOUSE14 => Self::Mouse14,
            OBS_KEY_MOUSE15 => Self::Mouse15,
            OBS_KEY_MOUSE16 => Self::Mouse16,
            OBS_KEY_MOUSE17 => Self::Mouse17,
            OBS_KEY_MOUSE18 => Self::Mouse18,
            OBS_KEY_MOUSE19 => Self::Mouse19,
            OBS_KEY_MOUSE20 => Self::Mouse20,
            OBS_KEY_MOUSE21 => Self::Mouse21,
            OBS_KEY_MOUSE22 => Self::Mouse22,
            OBS_KEY_MOUSE23 => Self::Mouse23,
            OBS_KEY_MOUSE24 => Self::Mouse24,
            OBS_KEY_MOUSE25 => Self::Mouse25,
            OBS_KEY_MOUSE26 => Self::Mouse26,
            OBS_KEY_MOUSE27 => Self::Mouse27,
            OBS_KEY_MOUSE28 => Self::Mouse28,
            OBS_KEY_MOUSE29 => Self::Mouse29,
            OBS_KEY_OPEN => Self::BackslashRt102,
            OBS_KEY_BACKSLASH_RT102 => Self::Open,
            OBS_KEY_FIND => Self::Find,
            OBS_KEY_REDO => Self::Redo,
            OBS_KEY_UNDO => Self::Undo,
            OBS_KEY_FRONT => Self::Front,
            OBS_KEY_PROPS => Self::Props,
            OBS_KEY_VK_CANCEL => Self::VkCancel,
            OBS_KEY_0x07 => Self::Key0x07,
            OBS_KEY_0x0A => Self::Key0x0a,
            OBS_KEY_0x0B => Self::Key0x0b,
            OBS_KEY_0x0E => Self::Key0x0e,
            OBS_KEY_0x0F => Self::Key0x0f,
            OBS_KEY_0x16 => Self::Key0x16,
            OBS_KEY_VK_JUNJA => Self::VkJunja,
            OBS_KEY_VK_FINAL => Self::VkFinal,
            OBS_KEY_0x1A => Self::Key0x1a,
            OBS_KEY_VK_ACCEPT => Self::VkAccept,
            OBS_KEY_VK_MODECHANGE => Self::VkModechange,
            OBS_KEY_VK_SELECT => Self::VkSelect,
            OBS_KEY_VK_PRINT => Self::VkPrint,
            OBS_KEY_VK_EXECUTE => Self::VkExecute,
            OBS_KEY_VK_HELP => Self::VkHelp,
            OBS_KEY_0x30 => Self::Key0x30,
            OBS_KEY_0x31 => Self::Key0x31,
            OBS_KEY_0x32 => Self::Key0x32,
            OBS_KEY_0x33 => Self::Key0x33,
            OBS_KEY_0x34 => Self::Key0x34,
            OBS_KEY_0x35 => Self::Key0x35,
            OBS_KEY_0x36 => Self::Key0x36,
            OBS_KEY_0x37 => Self::Key0x37,
            OBS_KEY_0x38 => Self::Key0x38,
            OBS_KEY_0x39 => Self::Key0x39,
            OBS_KEY_0x3A => Self::Key0x3a,
            OBS_KEY_0x3B => Self::Key0x3b,
            OBS_KEY_0x3C => Self::Key0x3c,
            OBS_KEY_0x3D => Self::Key0x3d,
            OBS_KEY_0x3E => Self::Key0x3e,
            OBS_KEY_0x3F => Self::Key0x3f,
            OBS_KEY_0x40 => Self::Key0x40,
            OBS_KEY_0x41 => Self::Key0x41,
            OBS_KEY_0x42 => Self::Key0x42,
            OBS_KEY_0x43 => Self::Key0x43,
            OBS_KEY_0x44 => Self::Key0x44,
            OBS_KEY_0x45 => Self::Key0x45,
            OBS_KEY_0x46 => Self::Key0x46,
            OBS_KEY_0x47 => Self::Key0x47,
            OBS_KEY_0x48 => Self::Key0x48,
            OBS_KEY_0x49 => Self::Key0x49,
            OBS_KEY_0x4A => Self::Key0x4a,
            OBS_KEY_0x4B => Self::Key0x4b,
            OBS_KEY_0x4C => Self::Key0x4c,
            OBS_KEY_0x4D => Self::Key0x4d,
            OBS_KEY_0x4E => Self::Key0x4e,
            OBS_KEY_0x4F => Self::Key0x4f,
            OBS_KEY_0x50 => Self::Key0x50,
            OBS_KEY_0x51 => Self::Key0x51,
            OBS_KEY_0x52 => Self::Key0x52,
            OBS_KEY_0x53 => Self::Key0x53,
            OBS_KEY_0x54 => Self::Key0x54,
            OBS_KEY_0x55 => Self::Key0x55,
            OBS_KEY_0x56 => Self::Key0x56,
            OBS_KEY_0x57 => Self::Key0x57,
            OBS_KEY_0x58 => Self::Key0x58,
            OBS_KEY_0x59 => Self::Key0x59,
            OBS_KEY_0x5A => Self::Key0x5a,
            OBS_KEY_VK_LWIN => Self::VkLwin,
            OBS_KEY_VK_RWIN => Self::VkRwin,
            OBS_KEY_VK_APPS => Self::VkApps,
            OBS_KEY_0x5E => Self::Key0x5e,
            OBS_KEY_VK_SLEEP => Self::VkSleep,
            OBS_KEY_VK_SEPARATOR => Self::VkSeparator,
            OBS_KEY_0x88 => Self::Key0x88,
            OBS_KEY_0x89 => Self::Key0x89,
            OBS_KEY_0x8A => Self::Key0x8a,
            OBS_KEY_0x8B => Self::Key0x8b,
            OBS_KEY_0x8C => Self::Key0x8c,
            OBS_KEY_0x8D => Self::Key0x8d,
            OBS_KEY_0x8E => Self::Key0x8e,
            OBS_KEY_0x8F => Self::Key0x8f,
            OBS_KEY_VK_OEM_FJ_JISHO => Self::VkOemFjJisho,
            OBS_KEY_VK_OEM_FJ_LOYA => Self::VkOemFjLoya,
            OBS_KEY_VK_OEM_FJ_ROYA => Self::VkOemFjRoya,
            OBS_KEY_0x97 => Self::Key0x97,
            OBS_KEY_0x98 => Self::Key0x98,
            OBS_KEY_0x99 => Self::Key0x99,
            OBS_KEY_0x9A => Self::Key0x9a,
            OBS_KEY_0x9B => Self::Key0x9b,
            OBS_KEY_0x9C => Self::Key0x9c,
            OBS_KEY_0x9D => Self::Key0x9d,
            OBS_KEY_0x9E => Self::Key0x9e,
            OBS_KEY_0x9F => Self::Key0x9f,
            OBS_KEY_VK_LSHIFT => Self::VkLshift,
            OBS_KEY_VK_RSHIFT => Self::VkRshift,
            OBS_KEY_VK_LCONTROL => Self::VkLcontrol,
            OBS_KEY_VK_RCONTROL => Self::VkRcontrol,
            OBS_KEY_VK_LMENU => Self::VkLmenu,
            OBS_KEY_VK_RMENU => Self::VkRmenu,
            OBS_KEY_VK_BROWSER_BACK => Self::VkBrowserBack,
            OBS_KEY_VK_BROWSER_FORWARD => Self::VkBrowserForward,
            OBS_KEY_VK_BROWSER_REFRESH => Self::VkBrowserRefresh,
            OBS_KEY_VK_BROWSER_STOP => Self::VkBrowserStop,
            OBS_KEY_VK_BROWSER_SEARCH => Self::VkBrowserSearch,
            OBS_KEY_VK_BROWSER_FAVORITES => Self::VkBrowserFavorites,
            OBS_KEY_VK_BROWSER_HOME => Self::VkBrowserHome,
            OBS_KEY_VK_VOLUME_MUTE => Self::VkVolumeMute,
            OBS_KEY_VK_VOLUME_DOWN => Self::VkVolumeDown,
            OBS_KEY_VK_VOLUME_UP => Self::VkVolumeUp,
            OBS_KEY_VK_MEDIA_NEXT_TRACK => Self::VkMediaNextTrack,
            OBS_KEY_VK_MEDIA_PREV_TRACK => Self::VkMediaPrevTrack,
            OBS_KEY_VK_MEDIA_STOP => Self::VkMediaStop,
            OBS_KEY_VK_MEDIA_PLAY_PAUSE => Self::VkMediaPlayPause,
            OBS_KEY_VK_LAUNCH_MAIL => Self::VkLaunchMail,
            OBS_KEY_VK_LAUNCH_MEDIA_SELECT => Self::VkLaunchMediaSelect,
            OBS_KEY_VK_LAUNCH_APP1 => Self::VkLaunchApp1,
            OBS_KEY_VK_LAUNCH_APP2 => Self::VkLaunchApp2,
            OBS_KEY_0xB8 => Self::Key0xb8,
            OBS_KEY_0xB9 => Self::Key0xb9,
            OBS_KEY_0xC1 => Self::Key0xc1,
            OBS_KEY_0xC2 => Self::Key0xc2,
            OBS_KEY_0xC3 => Self::Key0xc3,
            OBS_KEY_0xC4 => Self::Key0xc4,
            OBS_KEY_0xC5 => Self::Key0xc5,
            OBS_KEY_0xC6 => Self::Key0xc6,
            OBS_KEY_0xC7 => Self::Key0xc7,
            OBS_KEY_0xC8 => Self::Key0xc8,
            OBS_KEY_0xC9 => Self::Key0xc9,
            OBS_KEY_0xCA => Self::Key0xca,
            OBS_KEY_0xCB => Self::Key0xcb,
            OBS_KEY_0xCC => Self::Key0xcc,
            OBS_KEY_0xCD => Self::Key0xcd,
            OBS_KEY_0xCE => Self::Key0xce,
            OBS_KEY_0xCF => Self::Key0xcf,
            OBS_KEY_0xD0 => Self::Key0xd0,
            OBS_KEY_0xD1 => Self::Key0xd1,
            OBS_KEY_0xD2 => Self::Key0xd2,
            OBS_KEY_0xD3 => Self::Key0xd3,
            OBS_KEY_0xD4 => Self::Key0xd4,
            OBS_KEY_0xD5 => Self::Key0xd5,
            OBS_KEY_0xD6 => Self::Key0xd6,
            OBS_KEY_0xD7 => Self::Key0xd7,
            OBS_KEY_0xD8 => Self::Key0xd8,
            OBS_KEY_0xD9 => Self::Key0xd9,
            OBS_KEY_0xDA => Self::Key0xda,
            OBS_KEY_VK_OEM_8 => Self::VkOem8,
            OBS_KEY_0xE0 => Self::Key0xe0,
            OBS_KEY_VK_OEM_AX => Self::VkOemAx,
            OBS_KEY_VK_ICO_HELP => Self::VkIcoHelp,
            OBS_KEY_VK_ICO_00 => Self::VkIco00,
            OBS_KEY_VK_PROCESSKEY => Self::VkProcesskey,
            OBS_KEY_VK_ICO_CLEAR => Self::VkIcoClear,
            OBS_KEY_VK_PACKET => Self::VkPacket,
            OBS_KEY_0xE8 => Self::Key0xe8,
            OBS_KEY_VK_OEM_RESET => Self::VkOemReset,
            OBS_KEY_VK_OEM_JUMP => Self::VkOemJump,
            OBS_KEY_VK_OEM_PA1 => Self::VkOemPa1,
            OBS_KEY_VK_OEM_PA2 => Self::VkOemPa2,
            OBS_KEY_VK_OEM_PA3 => Self::VkOemPa3,
            OBS_KEY_VK_OEM_WSCTRL => Self::VkOemWsctrl,
            OBS_KEY_VK_OEM_CUSEL => Self::VkOemCusel,
            OBS_KEY_VK_OEM_ATTN => Self::VkOemAttn,
            OBS_KEY_VK_OEM_FINISH => Self::VkOemFinish,
            OBS_KEY_VK_OEM_COPY => Self::VkOemCopy,
            OBS_KEY_VK_OEM_AUTO => Self::VkOemAuto,
            OBS_KEY_VK_OEM_ENLW => Self::VkOemEnlw,
            OBS_KEY_VK_ATTN => Self::VkAttn,
            OBS_KEY_VK_CRSEL => Self::VkCrsel,
            OBS_KEY_VK_EXSEL => Self::VkExsel,
            OBS_KEY_VK_EREOF => Self::VkEreof,
            OBS_KEY_VK_PLAY => Self::VkPlay,
            OBS_KEY_VK_ZOOM => Self::VkZoom,
            OBS_KEY_VK_NONAME => Self::VkNoname,
            OBS_KEY_VK_PA1 => Self::VkPa1,
            OBS_KEY_VK_OEM_CLEAR => Self::VkOemClear,
            _ => Self::Unknown,
        })
    }

    fn to_native(self) -> libobs_sys::obs_key::Type {
        self as _
    }

    pub fn from_name(name: &str) -> Option<Self> {
        let name = name.cstr();

        Self::from_native(unsafe { libobs_sys::obs_key_from_name(name.as_ptr()) })
    }
}

#[derive(Clone, Copy)]
pub struct KeyCombination {
    pub modifiers: InteractionFlags,
    pub key: Key,
}

impl KeyCombination {
    pub fn from_native(value: libobs_sys::obs_key_combination) -> Option<Self> {
        Key::from_native(value.key).map(|key| Self {
            modifiers: InteractionFlags::from_bits_truncate(value.modifiers),
            key,
        })
    }

    pub fn to_native(self) -> libobs_sys::obs_key_combination {
        libobs_sys::obs_key_combination {
            modifiers: self.modifiers.bits(),
            key: self.key.to_native(),
        }
    }

    pub fn inject_event(self, pressed: bool) {
        unsafe { libobs_sys::obs_hotkey_inject_event(self.to_native(), pressed) };
    }
}

pub fn save_encoder(encoder: &Encoder<'_>) -> Data<'static> {
    Data::from_raw(unsafe { libobs_sys::obs_hotkeys_save_encoder(encoder.as_ptr()) })
}

pub fn save_output(output: &Output<'_>) -> Data<'static> {
    Data::from_raw(unsafe { libobs_sys::obs_hotkeys_save_output(output.as_ptr()) })
}

pub fn save_service(service: &Service<'_>) -> Data<'static> {
    Data::from_raw(unsafe { libobs_sys::obs_hotkeys_save_service(service.as_ptr()) })
}

pub fn save_source(source: &Source<'_>) -> Data<'static> {
    Data::from_raw(unsafe { libobs_sys::obs_hotkeys_save_source(source.as_ptr()) })
}

pub fn list() -> Vec<Hotkey> {
    list_instances(libobs_sys::obs_enum_hotkeys, Hotkey::from_raw)
}

pub fn list_bindings() -> Vec<HotkeyBinding> {
    list_instances(
        libobs_sys::obs_enum_hotkey_bindings,
        HotkeyBinding::from_raw,
    )
}

fn list_instances<R, I, T>(
    f: unsafe extern "C" fn(
        Option<unsafe extern "C" fn(*mut c_void, I, *mut R) -> bool>,
        *mut c_void,
    ),
    converter: fn(*mut R) -> T,
) -> Vec<T> {
    struct Param<R, T> {
        instances: Vec<T>,
        converter: fn(*mut R) -> T,
    }

    unsafe extern "C" fn callback<R, I, T>(param: *mut c_void, _id: I, raw: *mut R) -> bool {
        if !raw.is_null() {
            let param = &mut *param.cast::<Param<R, T>>();
            param.instances.push((param.converter)(raw));
        }

        true
    }

    let mut param = Param {
        instances: Vec::new(),
        converter,
    };

    unsafe {
        f(
            Some(callback::<R, I, T>),
            (&mut param as *mut Param<_, _>).cast(),
        )
    };

    param.instances
}
