[package]
name = "api-legacy"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.58"
image = { version = "0.24.2", default-features = false, features = ["jpeg", "png"] }
log = "0.4.17"
obs = { path = "../obs" }
parking_lot = "0.12.1"
prost = "0.10.4"
prost-types = "0.10.1"
tokio = { version = "1.19.2", features = ["fs", "rt", "sync"] }
tokio-stream = { version = "0.1.9", default-features = false, features = ["sync"] }
tonic = { version = "0.7.2", features = ["compression"] }

[build-dependencies]
tonic-build = { version = "0.7.2", features = ["compression"] }
