[package]
name = "api-legacy"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.69"
image = { version = "0.24.5", default-features = false, features = ["jpeg", "png"] }
log = "0.4.17"
obs = { path = "../obs" }
parking_lot = "0.12.1"
prost = "0.11.8"
prost-types = "0.11.8"
tokio = { version = "1.26.0", features = ["fs", "rt", "sync"] }
tokio-stream = { version = "0.1.12", default-features = false, features = ["sync"] }
tonic = { version = "0.8.3", features = ["gzip"] }

[build-dependencies]
tonic-build = "0.8.4"
