fn main() {
    tonic_build::configure()
        .build_server(false)
        .compile(
            &[
                "../api/proto/config.proto",
                "../api/proto/events.proto",
                "../api/proto/filters.proto",
                "../api/proto/general.proto",
                "../api/proto/hotkeys.proto",
                "../api/proto/inputs.proto",
                "../api/proto/media_inputs.proto",
                "../api/proto/outputs.proto",
                "../api/proto/profiles.proto",
                "../api/proto/projectors.proto",
                "../api/proto/recording.proto",
                "../api/proto/replay_buffer.proto",
                "../api/proto/scene_collections.proto",
                "../api/proto/scene_items.proto",
                "../api/proto/scenes.proto",
                "../api/proto/sources.proto",
                "../api/proto/streaming.proto",
                "../api/proto/transitions.proto",
                "../api/proto/virtual_cam.proto",
            ],
            &["../api/proto"],
        )
        .unwrap();
}
