[package]
name = "obs-client"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.75"
prost = "0.11.9"
prost-types = "0.11.9"
tokio = { version = "1.32.0", features = ["macros", "rt"] }
tonic = { version = "0.9.2", features = ["gzip"] }

[build-dependencies]
tonic-build = "0.9.2"
