fn main() {
    tonic_build::configure()
        .build_server(false)
        .compile(
            &[
                "../obs-remote/proto/events.proto",
                "../obs-remote/proto/general.proto",
                "../obs-remote/proto/media_control.proto",
                "../obs-remote/proto/outputs.proto",
                "../obs-remote/proto/profiles.proto",
                "../obs-remote/proto/recording.proto",
                "../obs-remote/proto/replay_buffer.proto",
                "../obs-remote/proto/scene_collections.proto",
                "../obs-remote/proto/scene_items.proto",
                "../obs-remote/proto/scenes.proto",
                "../obs-remote/proto/sources.proto",
                "../obs-remote/proto/streaming.proto",
                "../obs-remote/proto/studio_mode.proto",
                "../obs-remote/proto/transitions.proto",
                "../obs-remote/proto/virtual_cam.proto",
            ],
            &["../obs-remote/proto"],
        )
        .unwrap();

    tonic_build::configure()
        .build_server(false)
        .compile(
            &[
                "../obs-remote/proto/v5/config.proto",
                "../obs-remote/proto/v5/events.proto",
                "../obs-remote/proto/v5/filters.proto",
                "../obs-remote/proto/v5/general.proto",
                "../obs-remote/proto/v5/hotkeys.proto",
                "../obs-remote/proto/v5/inputs.proto",
                "../obs-remote/proto/v5/media_inputs.proto",
                "../obs-remote/proto/v5/outputs.proto",
                "../obs-remote/proto/v5/profiles.proto",
                "../obs-remote/proto/v5/projectors.proto",
                "../obs-remote/proto/v5/recording.proto",
                "../obs-remote/proto/v5/replay_buffer.proto",
                "../obs-remote/proto/v5/scene_collections.proto",
                "../obs-remote/proto/v5/scene_items.proto",
                "../obs-remote/proto/v5/scenes.proto",
                "../obs-remote/proto/v5/sources.proto",
                "../obs-remote/proto/v5/streaming.proto",
                "../obs-remote/proto/v5/transitions.proto",
                "../obs-remote/proto/v5/virtual_cam.proto",
            ],
            &["../obs-remote/proto"],
        )
        .unwrap();
}
