[package]
name = "api"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.55"
image = { version = "0.24.1", default-features = false, features = ["jpeg", "png"] }
log = "0.4.14"
obs = { path = "../obs" }
prost = "0.9.0"
prost-types = "0.9.0"
tokio = { version = "1.17.0", features = ["fs", "rt", "sync"] }
tokio-stream = { version = "0.1.8", default-features = false, features = ["sync"] }
tonic = { version = "0.6.2", features = ["compression"] }

[build-dependencies]
tonic-build = { version = "0.6.2", features = ["compression"] }
