[package]
name = "obs-remote"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
description = "Remote control OBS with gRPC"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.40"
log = { version = "0.4.14", features = ["std", "max_level_debug"] }
obs = { path = "../obs" }
prost = "0.7.0"
prost-types = "0.7.0"
tokio = { version = "1.5.0", features = ["macros", "rt", "sync"] }
tokio-stream = { version = "0.1.5", default-features = false, features = ["sync"] }
tonic = "0.4.3"

[build-dependencies]
tonic-build = "0.4.2"
