[package]
name = "libobs-sys"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
build = "build.rs"
license = "AGPL-3.0-only"

[dependencies]

[build-dependencies]
bindgen = { version = "0.59.2", default-features = false, features = ["runtime", "which-rustfmt"] }

[target.'cfg(all(unix, not(target_os = "macos")))'.build-dependencies]
pkg-config = "0.3.24"

[target.'cfg(windows)'.build-dependencies]
cc = "1.0.73"
regex = "1.5.4"
winreg = "0.10.1"
